export const cardDetails = [
  {
    grower: "Seed Factory",
    area: "lorem ipsum doler",
    capital: "100 Ether",
    estimatedReturn: "%50",
    duration: "14/04/2023",
    id: "1",
  },
  {
    grower: "Seed Factory",
    area: "lorem ipsum doler",
    capital: "100 Ether",
    estimatedReturn: "%50",
    duration: "14/04/2023",
    id: "2",
  },
  {
    grower: "Seed Factory",
    area: "lorem ipsum doler",
    capital: "100 Ether",
    estimatedReturn: "%50",
    duration: "14/04/2023",
    id: "3",
  },
  {
    grower: "Seed Factory",
    area: "lorem ipsum doler",
    capital: "100 Ether",
    estimatedReturn: "%50",
    duration: "14/04/2023",
    id: "4",
  },
  {
    grower: "Seed Factory",
    area: "lorem ipsum doler",
    capital: "100 Ether",
    estimatedReturn: "%50",
    duration: "14/04/2023",
    id: "5",
  },
  {
    grower: "Seed Factory",
    area: "lorem ipsum doler",
    capital: "100 Ether",
    estimatedReturn: "%50",
    duration: "14/04/2023",
    id: "6",
  },
];
